# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7be83c41fc4a9b78d23ad1a079719ed91495f84a84bcd69b5a7fb0e5e8fb457ea5599507ec87812cb40a627b5729e330007b15b6f8b943376ae37ca7feb97bab

test:
  secret_key_base: 9d698da10833512ce312622b999ccaef377aaf33a5dbf1cbb162e306c47f0263362430a62ac49a12a71427284f0feb92ac3cf16a54c710b5ec17e4a766bba54e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
